# Generated by Django 2.1.4 on 2019-05-21 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=40)),
                ('info', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=4)),
                ('ps', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '企业数据',
                'verbose_name_plural': '企业表',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='', max_length=2, null=True)),
                ('age', models.IntegerField(null=True)),
                ('edu', models.CharField(default='', max_length=4, null=True)),
                ('super', models.CharField(default='', max_length=10, null=True)),
                ('tech', models.CharField(default='', max_length=10, null=True)),
                ('tel', models.CharField(default='', max_length=14, null=True)),
                ('K1', models.IntegerField(null=True)),
                ('K2', models.IntegerField(null=True)),
                ('exp', models.IntegerField(null=True)),
                ('wantJob', models.CharField(default='', max_length=20, null=True)),
                ('school', models.CharField(default='', max_length=20, null=True)),
                ('gzjl', models.CharField(default='', max_length=200, null=True)),
                ('jybj', models.CharField(default='', max_length=200, null=True)),
                ('zwjs', models.CharField(default='', max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '简历数据',
                'verbose_name_plural': '简历表',
            },
        ),
        migrations.CreateModel(
            name='CV2Zp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('zp_id', models.IntegerField()),
                ('com_id', models.CharField(max_length=10, null=True)),
                ('jobName', models.CharField(max_length=40, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
            ],
            options={
                'verbose_name': '投递关系数据',
                'verbose_name_plural': '投递关系表',
            },
        ),
        migrations.CreateModel(
            name='Zp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=30)),
                ('jobType', models.CharField(max_length=40)),
                ('jobName', models.CharField(max_length=40)),
                ('W1', models.IntegerField()),
                ('W2', models.IntegerField()),
                ('eduLevel', models.CharField(max_length=10)),
                ('K1', models.FloatField()),
                ('K2', models.FloatField()),
                ('info', models.CharField(default='', max_length=200, null=True)),
                ('addr', models.CharField(default='', max_length=60, null=True)),
                ('com_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '招聘数据',
                'verbose_name_plural': '招聘表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cv2zp',
            unique_together={('user_id', 'zp_id')},
        ),
    ]
